#!/bin/sh

sed -i '/application\/x-java-archive/d' /usr/share/applications/mimeinfo.cache
sed -i '/application\/x-java-archive/d' /usr/share/applications/gnome-mimeapps.list

for item in $(ls /usr/share/applications/)
do
	if [ $item != 'mimeinfo.cache' ] 
	then
		#echo $item
		sed -i 's/application\/x-java-archive;//g' /usr/share/applications/$item
	fi
done


exit 0
